services:
  server:
    build:
      context: ./server
      args:
        HOST: docker
        REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
  
  client:
    build:
      context: ./client
      args:
        SERVER_HOST: server
        SERVER_PORT: 3000
    depends_on:
      - server

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
