services:
  server:
    build:
      context: ./server
    ports:
      - 5000:3000
  
  client:
    build:
      context: ./client
      args:
        SERVER_HOST: server
        SERVER_PORT: 3000
    depends_on:
      - server
