services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        HOST: docker
        REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
